version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - libQualityDB:/var/lib/mysql
    env_file:
      - .env
volumes:
  libQualityDB: {}