version: "3.8"
services:
  web:
    container_name: backend
    image: libquality:latest
    ports:
      - "3000:3000"
    links:
      - mysql
    env_file:
      - .env
    environment:
      - DB_HOST=mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - libQualityDB:/var/lib/mysql
    env_file:
      - .env
volumes:
  libQualityDB: {}